# Author : Alex Rose 2015/03
# Description : This script will initialize every individual web server hosted on the container

import urllib
from pymongo import MongoClient
import os
import pwd
import subprocess
import sys
import threading
import time
import json


# Custom resources
from auth import Auth
from colors import colors

def launch(user_name, args, cwd = '/home'):
    pw_record = pwd.getpwnam(user_name)
    user_name      = pw_record.pw_name
    user_home_dir  = pw_record.pw_dir
    user_uid       = pw_record.pw_uid
    user_gid       = pw_record.pw_gid
    env = os.environ.copy()
    env[ 'HOME'     ]  = user_home_dir
    env[ 'LOGNAME'  ]  = user_name
    env[ 'PWD'      ]  = cwd
    env[ 'USER'     ]  = user_name
    #report_ids('starting ' + str(args))
    process = subprocess.Popen(
        args, preexec_fn=demote(user_uid, user_gid), cwd=cwd, env=env
    )
    #result = process.wait()


    thread = threading.Thread(target=get_result, args=(process, user_name))
    thread.daemon = False
    thread.start()

def get_result(process, user):
    print 'Starting', user
    time.sleep(10)
    #report_ids('finished')
    if process.poll() == 1 :
        print user + ' success';
    else:
        print colors.WARNING + '[WARNING] ' + user + ' returned code ' + str(process.poll()) + colors.ENDC

def demote(user_uid, user_gid):
    def result():
#        report_ids('starting demotion')
        os.setgid(user_gid)
        os.setuid(user_uid)
#        report_ids('finished demotion')
    return result


def report_ids(msg):
    print 'uid, gid = %d, %d; %s' % (os.getuid(), os.getgid(), msg)


username = Auth.username
password = urllib.quote_plus(Auth.password)

string = 'mongodb//'+username+':'+password+'@127.0.0.1:27017'

c = MongoClient()
c.admin.authenticate(Auth.username, Auth.password)

routes = {'_comment' : 'This file is generated by init_nodes.py'}

users = c.admin_step.users.find({"web":{'$exists': True}})
for user in users:
	for web in user['web']:
	#print user['web']['home']
		script = web['home'] + '/.web_init.sh'
	
		print "Running script", script
		launch(web['user'], script, web['home'])

		routes[web['addr']] = int(web['port'])
		
		if 'www' in web and web['www'] == True:
			routes['www.' + web['addr']] = int(web['port'])


f = open('/root/routes.js', 'w')
f.write(json.dumps(routes))
f.write('\n')
f.close()
